### ISSUE TITLE
obfuscate wp-admin/wp-login to reduce spam

### ISSUE THREAD

**Issue by wxl** [linuxpadawan/site#2]
[Here](https://managewp.com/change-your-wordpress-login-url)'s an example of how to rename these pages to reduce spam. [Here](https://wordpress.org/support/topic/how-to-change-from-wp-loginphp-to-login)'s an option that doesn't require a plugin— and talks about integrating with BuddyPress.

**Comment by teward** [comment]
The logon page has been obfuscated for admin, I believe.

XMLRPC is also shut off at the web server level for now; I didn't want to 'delete' any files Wordpress might need.

**Comment by ghost** [comment]
I'm assuming this is fixed?

**Comment by wxl** [comment]
Yep. Close it!
