### ISSUE TITLE
MoinMoin to MediaWiki migration

### ISSUE THREAD

**Issue by wxl** [linuxpadawan/site#4]
This is essential. Without the wiki, we're kind of screwed. We either need to put MoinMoin back up (ugh, no thank you) or deal with the migration. MediaWiki has a [page](https://www.mediawiki.org/wiki/MoinMoin) on migration, with a particular [script](https://github.com/okfn/moinmoin2mediawiki) being the suggested option. 

However, the problem is that for some reason our MoinMoin doesn't have the users directories it expects. I would suggest we manually create users and then delete the part of the script that deals with the migration of users. That or do everything manually.

**Comment by tsimonq2** [comment]
Bump, it seems like there is progress but there is still work to do. What's the status of this?

**Comment by wxl** [comment]
Well, we could wait for Ubuntu to switch over the MediaWiki, stay close to the development, and see how we can leverage it for our own uses.

…or we could just move everything over by hand. This has been discussed a bit, but no one's really had the time to do it. We just need to start page by page. Not leave it on any one person's shoulders. You in? We could get @teward to make credentials for us all. @belkinsa are you willing to help?

**Comment by tsimonq2** [comment]
@wxl Totally, I'd love to help. @teward, could I please get some credentials? :)

**Comment by teward** [comment]
I have a little bit of a security crisis on my hands with one of my servers testing as vulnerable on one of my custom apps I have to keep up - that's my current priority, I'll make credentials when I can but that's not going to be my highest priority.

**Comment by wxl** [comment]
no problem. you could also nominate one of us to be the admin and we could make new users.

**Comment by tsimonq2** [comment]
@wxl thanks to @teward, I now have access and I will start the transfer when I have the time.

**Comment by ghost** [comment]
@wxl I'm not ready to help just let, but maybe in a week or two, I will be.  Sorry.

**Comment by ghost** [comment]
Is this done?

**Comment by teward** [comment]
@belkinsa @wxl was working on it last, I don't know exactly how far along we are.

**Comment by ghost** [comment]
Alright, I will close it.  If the issue arises again, we can open a new one.
